core/urls.py
from django.conf.urls import patterns, include, url
from .views import *
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
    url(r'^$', Home.as_view(), name='home'),
    url(r'^user/', include('registration.backends.simple.urls')),
    url(r'^user/', include('django.contrib.auth.urls')),
    url(r'^candidates/$', Candidate.as_view(), name='candidates'),
    url(r'^question/create/$', login_required(QuestionCreateView.as_view()), name='question_create'),
    url(r'question/$', login_required(QuestionListView.as_view()), name='question_list'),
    url(r'^question/(?P<pk>\d+)/$', login_required(QuestionDetailView.as_view()), name='question_detail'),
    url(r'^question/update/(?P<pk>\d+)/$', login_required(QuestionUpdateView.as_view()), name='question_update'),
    url(r'^question/delete/(?P<pk>\d+)/$', login_required(QuestionDeleteView.as_view()), name='question_delete'),
    url(r'^question/(?P<pk>\d+)/answer/create/$', login_required(AnswerCreateView.as_view()), name='answer_create'),
    url(r'^question/(?P<question_pk>\d+)/answer/update/(?P<answer_pk>\d+)/$', login_required(AnswerUpdateView.as_view()), name='answer_update'),
    url(r'^question/(?P<question_pk>\d+)/answer/delete/(?P<answer_pk>\d+)/$', login_required(AnswerDeleteView.as_view()), name='answer_delete'),
    url(r'^vote/$', login_required(VoteFormView.as_view()), name='vote'),
    url(r'^user/(?P<slug>\w+)/$', login_required(UserDetailView.as_view()), name='user_detail'),
    url(r'^user/update/(?P<slug>\w+)/$', login_required(UserUpdateView.as_view()), name='user_update'),
    url(r'^user/delete/(?P<slug>\w+)/$', login_required(UserDeleteView.as_view()), name='user_delete'),
    url(r'^search/$', login_required(SearchQuestionListView.as_view()), name='search'),
)

president_review/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('core.urls')),

]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

# Create your models here.
VISIBILITY_CHOICES = (
(0, 'Public'),
(1, 'Anonymous'),
)

candidate_options = (
(0, ''),
(1, 'Jeb Bush'),
(2, 'Ben Carson'),
(3, 'Hillary Clinton'),
(4, 'Ted Cruz'),
(5, 'Lawrence Lessig'),
(6, 'Martin OMalley'),
(7, 'Marco Rubio'),
(8, 'Bernie Sanders'),
(9, 'Donald Trump'),
(10, 'Guido Lang'),
)

class Question(models.Model):
  title = models.IntegerField(choices=candidate_options, default=0)
  name = models.CharField(max_length=300)
  email = models.EmailField(max_length=254, blank=False, null= True, unique= False)
  review = models.TextField(null=True, blank=True)
  created_at = models.DateTimeField(auto_now_add=True)
  user = models.ForeignKey(User)
  visibility = models.IntegerField(choices=VISIBILITY_CHOICES, default=0)

  def __unicode__(self):
    return self.name

  def get_absolute_url(self):
    return reverse("question_detail", args=[self.id])

class Answer(models.Model):
    question = models.ForeignKey(Question)
    user = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add=True)
    opinion = models.TextField()
    visibility = models.IntegerField(choices=VISIBILITY_CHOICES, default=0)

    def __unicode__(self):
        return self.opinion

class Vote(models.Model):
    user = models.ForeignKey(User)
    question = models.ForeignKey(Question, blank=True, null=True)
    answer = models.ForeignKey(Answer, blank=True, null=True)

    def __unicode__(self):
        return "%s upvoted" % (self.user.username)

templates/question/question_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<p class="lead">Are you sure you want to delete "{{ question.get_title_display }}" review?</p>
<form method="post" action="">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Delete</button>
</form>
{% endblock %}

templates/question/question_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ question.name }}</h1>
<p>{{ question.review }}</p>
<p>Asked {% if question.visibility == 0 %} by <a href="{% url 'user_detail' slug=question.user.username %}">{{ question.user.username }}</a> {% endif %} on {{ question.created_at }}</p>
{% if question.user == user %}
<p><a href="{% url 'question_update' pk=question.id %}">Edit review</a></p>
<p><a href="{% url 'question_delete' pk=question.id %}">Delete review</a></p>
{% endif %}
{% if answers.count > 0 %}
<h3>{{ answers.count }} Answer{{ answers.count|pluralize }}:</h3>
{% endif %}
{% for answer in answers %}
<div class="panel">
    <p>{{ answer.opinion }}</p>
    {% if answer.user == user %}
      <p><a href="{% url 'answer_update' question_pk=question.id answer_pk=answer.id %}">Edit opinion</a></p>
      <p><a href="{% url 'answer_delete' question_pk=question.id answer_pk=answer.id %}">Delete opinion</a></p>
    {% endif %}
    <p>Answered {% if answer.visibility == 0 %} by <a href="{% url 'user_detail' slug=answer.user.username %}">{{ answer.user.username }}</a> {% endif %} on {{ answer.created_at }}</p>
<form method="post" action="{% url 'vote' %}">
    <span class="badge">{{ answer.vote_set.all.count }} Vote{{  answer.vote_set.all.count|pluralize }}</span>
    {% csrf_token %}
    <input type="hidden" name="answer" value="{{ answer.id }}" />
    <input type="hidden" name="question" value="{{ question.id }}" />
    <input type="hidden" name="user" value="{{ user.id }}" />
    {% if answer in user_votes %}
        <button class="btn btn-link">
          <span class="glyphicon glyphicon-thumbs-down"></span>
        </button>
    {% else %}
        <button class="btn btn-link">
          <span class="glyphicon glyphicon-thumbs-up"></span>
        </button>
    {% endif %}
</form>
</div>
{% endfor %}
{% if not user_answers %}
<p><a href="{% url 'answer_create' pk=question.id %}">Write opinion</a></p>
{% endif %}
{% endblock %}

templates/question/question_form.html
<head>
      <title>Review a Candidate</title>
</head>
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
<div class="row">
<div class="col-lg-6">
<form method="post" action="">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>
</div>
{% endblock %}

templates/question/question_list.html
<head>
      <title>Reviews</title>
</head>
{% extends 'base.html' %}
{% block content %}
{% for question in object_list %}
<div class="panel">
    <h3>{% if question.visibility == 0 %}{{ question.name }} {% else %} A Ghost {% endif %} reviewed <a href="{{ question.get_absolute_url }}">{{ question.get_title_display }}</a></h3>
    <p>Asked {% if question.visibility == 0 %} by <a href="{% url 'user_detail' slug=question.user.username %}">{{ question.user.username }}</a> {% endif %} on {{ question.created_at }}</p>
      <form method="post" action="{% url 'vote' %}">
      <span class="badge">{{ question.answer_set.all.count }} Answer{{  question.answer_set.all.count|pluralize }}        </span>
        <span class="badge">{{ question.vote_set.all.count }} Vote{{ question.vote_set.all.count|pluralize }}</span>
        {% csrf_token %}
        <input type="hidden" name="question" value="{{ question.id }}" />
        <input type="hidden" name="user" value="{{ user.id }}" />
            {% if question in user_votes %}
            <button class="btn btn-link">
              <span class="glyphicon glyphicon-thumbs-down"></span>
            </button>
            {% else %}
            <button class="btn btn-link">
              <span class="glyphicon glyphicon-thumbs-up"></span>
            </button>
            {% endif %}
        </form>
</div>
{% empty %}
<p>No results found.</p>
{% endfor %}
{% if is_paginated %}
<nav>
    <ul class="pager">
        {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% endif %}
        {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">Next</a></li>
        {% endif %}
    </ul>
</nav>
{% endif %}
{% endblock %}